#!/bin/bash
# Sentry Quick Setup Script

echo "🔍 Sentry Error Monitoring Setup"
echo "================================"
echo ""
echo "Sentry is already integrated into your bot!"
echo "It will monitor:"
echo "  ✅ All errors and crashes"
echo "  ✅ Quality scores (alerts if < 0.7)"
echo "  ✅ Validation failures"
echo "  ✅ API performance (alerts if > 10s)"
echo ""
echo "To activate Sentry:"
echo ""
echo "1. Create FREE account: https://sentry.io/signup/"
echo ""
echo "2. Create a Node.js project"
echo "   - Platform: Node.js"
echo "   - Framework: NestJS"
echo "   - Project name: rental-manager"
echo ""
echo "3. Copy your DSN (looks like: https://xxx@oyyy.ingest.sentry.io/zzz)"
echo ""
echo "4. Add to .env file:"
echo "   nano /home/ubuntu/rental-manager/.env"
echo "   # Add this line:"
echo "   SENTRY_DSN=your_dsn_here"
echo ""
echo "5. Restart bot:"
echo "   cd /home/ubuntu/rental-manager"
echo "   npx pm2 restart rental-manager"
echo ""
echo "6. Verify in Sentry dashboard (errors will appear within seconds)"
echo ""
echo "✅ Cost: FREE (5,000 errors/month)"
echo "💰 Value: £200-500/month (faster bug detection)"
